name: Test

on:
  push:
    branches: ["dev"]

env:
  new_tag: v1.0.0

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
    - name: Test json string
      run: |
        echo ::set-env name=repo::${GITHUB_REPOSITORY#*/}
        echo '{"project": "${{ env.repo }}","tag": "${{ env.new_tag }}"}'